#!/bin/bash

set -e

#  should match __pxe_location
if [ "x$URI_PATH" = "x" ]
then
  URI_PATH=http://static/pxe/vmware/esx-installer
fi

if [ ! $( which xorriso ) ]
then
  echo "xorriso not found, please install"
  exit 1
fi

if [ "x$1" = "x" ]
then
  echo "Specify a iso file"
  exit 1
fi

if [ "x$2" = "x" ]
then
  echo "Specify a target directory"
  exit 1
fi

ISO_FILE="$1"
TARGET_DIR="$2"

if [ ! -r "$ISO_FILE" ] || [ $( file -L -b --mime-type "$ISO_FILE" ) != "application/x-iso9660-image" ]
then
  echo "$ISO_FILE must be readable and an iso file"
  exit 1
fi

echo "Extracting ISO..."
file_list=$( xorriso -osirrox on -indev "$ISO_FILE" -lsl | grep -v '^d' | grep -v \.DISCINFO | awk '{print $9}' )
if [ "x$file_list" = "x" ]
then
  echo "Error getting file list from iso"
  exit 1
fi

for file in $file_list;
do
  # xorriso list adds ' arround the name, strip that
  file=${file//\'/}
  target_file=$( echo $file | tr '[:upper:]' '[:lower:]' )
  echo "extracting $target_file..."
  xorriso -osirrox on -indev "$ISO_FILE" -extract_single $file $TARGET_DIR/$target_file 2> /dev/null
done

echo "Configuring boot.cfg..."
sed s#/#${URI_PATH}\/#g -i $TARGET_DIR/boot.cfg
sed s/"kernelopt=runweasel"/""/ -i $TARGET_DIR/boot.cfg

echo "Done"
