#ifndef CONFIG_LOCAL_SERIAL_H
#define CONFIG_LOCAL_SERIAL_H

#if(T3KTON_COM)
#undef COMCONSOLE

#if(T3KTON_COM == 1)
#define COMCONSOLE COM1

#elif(T3KTON_COM == 2)
#define COMCONSOLE COM2

#elif(T3KTON_COM == 3)
#define COMCONSOLE COM3

#elif(T3KTON_COM == 4)
#define COMCONSOLE COM4

#endif /* T3TKTON_SOL */

#endif /* T3TKTON_SOL */


#endif /* CONFIG_LOCAL_SERIAL */
