[ structure.centos-base ]
  description = 'Base CentOS'
  parents = [ 'linux-base' ]
  config_values = { 'installer_pxe' = 'centos', 'mirror_server' = 'mirror.centos.org', 'distro' = 'centos' }

[ structure.centos-6-base]
  description = 'Base CentOS 6'
  parents = [ 'centos-base' ]
  config_values = { 'distro_version' = '6' }

[ structure.centos-7-base]
  description = 'Base CentOS 7'
  parents = [ 'centos-base' ]
  config_values = { 'distro_version' = '7' }
